# pragma warning disable CA1416 // Validate platform compatibility

using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using LotComPrinter.Models.Datasources;
using LotComPrinter.Models.Exceptions;
using LotComPrinter.Models.Services;

namespace LotComPrinter.Models.Datatypes;

/// <summary>
/// Base class for Physical Label types that can be printed by the LotCom Application.
/// </summary>
public class Label
{
    /// <summary>
    /// A LabelDimensions object that provides design constants for the Label.
    /// </summary>
    private readonly LabelDimensions Dimensions;

    /// <summary>
    /// A Bitmap image of the Label generated by the object's properties.
    /// </summary>
    private Bitmap? Image;

    /// <summary>
    /// The Font Group object for small text on the Label.
    /// </summary>
    private System.Drawing.Font? FontSmall;

    /// <summary>
    /// The Font Group object for medium text on the Label.
    /// </summary>
    private System.Drawing.Font? FontMedium;

    /// <summary>
    /// The Font Group object for large text on the Label.
    /// </summary>
    private System.Drawing.Font? FontLarge;

    /// <summary>
    /// Sets Image to a new, pure-white bitmap image to use as a Label base.
    /// </summary>
    private void LoadBase() 
    {
        int LabelSize = Dimensions.Dimension;
        // create a new white Label Base
        Bitmap Base = new Bitmap(LabelSize, LabelSize, System.Drawing.Imaging.PixelFormat.Format32bppArgb);
        // create a new Drawing Surface and draw all white to the base
        using (Graphics Surface = Graphics.FromImage(Base)) 
        {
            Rectangle ImageSize = new(0, 0, LabelSize, LabelSize);
            Surface.FillRectangle(Brushes.White, ImageSize);
        }
        Image = Base;
    }

    /// <summary>
    /// Loads the Small, Medium, and Large fonts from the System and stores them in their respective properties.
    /// </summary>
    /// <exception cref="SystemException"></exception>
    private void LoadFonts()
    {
        FontFamily? Arial;
        try 
        {
            Arial = new FontFamily("Arial");
        } 
        catch 
        {
            throw new SystemException("Could not find Arial Font Group in the System.");
        }
        FontSmall = new System.Drawing.Font(Arial!, Dimensions.TextSizeSmall);
        FontMedium = new System.Drawing.Font(Arial!, Dimensions.TextSizeMedium);
        FontLarge = new System.Drawing.Font(Arial!, Dimensions.TextSizeLarge);
        // confirm there are fonts set in the font properties
        if (FontSmall is null || FontMedium is null || FontLarge is null)
        {
            throw new SystemException("One or more Label Font was not configured successfully.");
        }
    }

    /// <summary>
    /// Creates a new Label that can be used to Print a Physical version of the configured object.
    /// </summary>
    /// <param name="Dimensions"></param>
    /// <exception cref="LabelBuildException"></exception>
    public Label(LabelDimensions Dimensions)
    {
        // configure the Label's design and dimensions
        this.Dimensions = Dimensions;
        // load a new Label base and load the Label's fonts
        LoadBase();
        try
        {
            LoadFonts();
        }
        catch (Exception _ex)
        {
            throw new SystemException($"Failed to configure the Label's fonts due to the following error:\n{_ex.Message}.");
        }
    }

    /// <summary>
    /// Access the current Bitmap image assigned to the Label object.
    /// </summary>
    /// <returns>A Bitmap image of the Label.</returns>
    public Bitmap GetImage() 
    {
        if (Image is not null)
        {
            return Image;
        }
        else
        {
            throw new NullReferenceException("There is no Image available to retrieve from this Label object.");
        }
    }

    /// <summary>
    /// Writes Header text to the Label using the configured Heading Anchors.
    /// </summary>
    /// <param name="HeadingText">The text to write.</param>
    /// <returns></returns>
    public async Task AddHeaderAsync(string HeadingText) 
    {
        // start a new CPU thread to apply the header to the Label Base
        await Task.Run(() => 
        {
            if (Image is null)
            {
                throw new NullReferenceException("Cannot apply a Header to a blank Label.");
            }
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Heading text
            Surface.DrawString
            (
                HeadingText,
                FontLarge!,
                Brushes.Black,
                Dimensions.HeadingHorizontalAnchor,
                Dimensions.HeadingVerticalAnchor
            );
            Surface.Flush();
        });
    }


    public async Task AddSubHeadingAsync(string SubHeadingText)
    {
        // start a new CPU thread to apply the Sub-heading to the Label Base
        await Task.Run(() => 
        {
            if (Image is null)
            {
                throw new NullReferenceException("Cannot apply a Sub-Heading to a blank Label.");
            }
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Heading text
            Surface.DrawString
            (
                SubHeadingText,
                FontLarge!,
                Brushes.Black,
                Dimensions.SubHeadingHorizontalAnchor,
                Dimensions.SubHeadingVerticalAnchor
            );
            Surface.Flush();
        });
    }

    /// <summary>
    /// Writes Body Title text to the Label using the configured Body Title Anchors.
    /// </summary>
    /// <param name="Text"></param>
    /// <returns></returns>
    public async Task AddBodyTitleAsync(string Text)
    {
        // start a new CPU thread to apply the Body Title to the Label Base
        await Task.Run(() =>
        {
            if (Image is null)
            {
                throw new NullReferenceException("Cannot apply a Body Title to a blank Label.");
            }
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Body Title text
            Surface.DrawString
            (
                Text,
                FontMedium!,
                Brushes.Black,
                Dimensions.BodyTitleHorizontalAnchor,
                Dimensions.BodyTitleVerticalAnchor
            );
            Surface.Flush();
        });
    }

    /// <summary>
    /// Adds a QR Code to the Label using the configured QR Code Anchors.
    /// </summary>
    /// <param name="LabelCode"></param>
    /// <returns></returns>
    public async Task AddQRCodeAsync(QRCode LabelCode) 
    {
        // start a new CPU thread to apply the QR code to the Label Base
        await Task.Run(() => 
        {
            if (Image is null)
            {
                throw new NullReferenceException("Cannot apply a QR Code to a blank Label.");
            }
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.CompositingMode = CompositingMode.SourceOver;
            Surface.CompositingQuality = CompositingQuality.HighQuality;
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            // resize and draw the QR Code
            Bitmap LabelCodeImage = Resizer.ResizeImage
            (
                LabelCode.Code!,
                Dimensions.CodeDimension,
                Dimensions.CodeDimension
            );
            Surface.DrawImage
            (
                LabelCodeImage,
                Dimensions.CodeHorizontalAnchor,
                Dimensions.CodeVerticalAnchor
            );
            Surface.Flush();
        });
    }

    /// <summary>
    /// Adds data fields to the Label using the configured Body Anchors.
    /// </summary>
    /// <param name="Fields"></param>
    /// <returns></returns>
    public async Task AddBodyTextAsync(List<string> Fields)
    {
        // start a new CPU thread to apply the Label Fields to the Label Base
        await Task.Run(() => 
        {
            // combine the Fields into a string deliniated by newlines
            string LabelFieldsBody = "";
            foreach (string _field in Fields) 
            {
                // if the field is the Part info, do not include the Part Name
                if (_field.Contains("Part")) 
                {
                    LabelFieldsBody += $"{_field.Split("\n")[0]}\n";
                // add the field as normal
                } 
                else 
                {
                    LabelFieldsBody += $"{_field}\n";
                }
            }
            if (Image is null)
            {
                throw new NullReferenceException("Cannot apply a QR Code to a blank Label.");
            }
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Heading text
            Surface.DrawString
            (
                LabelFieldsBody,
                FontSmall!,
                Brushes.Black,
                Dimensions.BodyHorizontalAnchor,
                Dimensions.BodyVerticalAnchor
            );
            Surface.Flush();
        });
    }
}

# pragma warning restore CA1416 // Validate platform compatibility