using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using LotCoMPrinter.Models.Services;

namespace LotCoMPrinter.Models.Datasources;

# pragma warning disable CA1416 // Validate platform compatibility

public class BasketLabel 
{
    /// <summary>
    /// The length of each side of the Label (square).
    /// Default is 1440.
    /// </summary>
    private int LabelDimension = 1440;

    /// <summary>
    /// The length of each side of the QR Code on the Label (square).
    /// Default is 600.
    /// </summary>
    private int CodeDimension = 600;

    /// <summary>
    /// The font size for small text on the Label.
    /// Default is 42.
    /// </summary>
    private int TextSizeSmall = 42;

    /// <summary>
    /// The font size for medium text on the Label.
    /// Default is 76.
    /// </summary>
    private int TextSizeMedium = 76;
    
    /// <summary>
    /// The font size for large text on the Label.
    /// Default is 192.
    /// </summary>
    private int TextSizeLarge = 192;

    /// <summary>
    /// Padding width/height applied between each item on the Label.
    /// Default is 12.
    /// </summary>
    private int LabelInternalPadding = 12;

    /// <summary>
    /// The horizontal position of the Label's Heading text.
    /// Default is dependent on the DPI Scale of the machine.
    /// </summary>
    private int LabelHeadingX;

    /// <summary>
    /// The vertical position of the Label's Heading text.
    /// Default is dependent on the DPI Scale of the machine.
    /// </summary>
    private int LabelHeadingY;
    
    /// <summary>
    /// The horizontal position of the Label's Part Name text.
    /// Default is dependent on the DPI Scale of the machine.
    /// </summary>
    private int LabelPartNameX;

    /// <summary>
    /// The vertical position of the Label's Part Name text.
    /// Default is dependent on the DPI Scale of the machine.
    /// </summary>
    private int LabelPartNameY;
    
    /// <summary>
    /// The horizontal (left) position of the QR Code on the Label.
    /// Default is dependent on the DPI Scale of the machine.
    /// </summary>
    private int CodePositionX1;

    /// <summary>
    /// The vertical (top) position of the QR Code on the Label.
    /// Default is dependent on the DPI Scale of the machine.
    /// </summary>
    private int CodePositionY1;

    /// <summary>
    /// The horizontal position of the Label's Data Fields text.
    /// Default is dependent on the DPI Scale of the machine.
    /// </summary>
    private int LabelFieldsX;

    /// <summary>
    /// The vertical position of the Label's Data Fields text.
    /// Default is dependent on the DPI Scale of the machine.
    /// </summary>
    private int LabelFieldsY;

    /// <summary>
    /// A Bitmap image of the Label generated by the object's properties.
    /// </summary>
    private readonly Bitmap Image;

    /// <summary>
    /// The Font Group object for small text on the Label.
    /// </summary>
    private readonly System.Drawing.Font FontSmall;

    /// <summary>
    /// The Font Group object for medium text on the Label.
    /// </summary>
    private readonly System.Drawing.Font FontMedium;

    /// <summary>
    /// The Font Group object for large text on the Label.
    /// </summary>
    private readonly System.Drawing.Font FontLarge;

    /// <summary>
    /// Converts the Label's internal dimension values to match the DPI scaling of the Device.
    /// Multiplies the default values by the set DPI scale.
    /// </summary>
    private void ConfigureLabelDimensions() 
    {
        // retreive the DPI scale for the device's display
        double DpiScale = DpiUtilities.GetDeviceDpiScale();
        // scale the Label's dimensions to the DPI
        LabelDimension = Convert.ToInt32(LabelDimension * DpiScale);
        CodeDimension = Convert.ToInt32(CodeDimension * DpiScale);
        TextSizeSmall = Convert.ToInt32(TextSizeSmall * DpiScale);
        TextSizeMedium = Convert.ToInt32(TextSizeMedium * DpiScale);
        TextSizeLarge = Convert.ToInt32(TextSizeLarge * DpiScale);
        LabelInternalPadding = Convert.ToInt32(LabelInternalPadding * DpiScale);
        LabelHeadingX = Convert.ToInt32(-56 * DpiScale + LabelInternalPadding);
        LabelHeadingY = Convert.ToInt32(-28 * DpiScale + LabelInternalPadding); 
        LabelPartNameX = LabelInternalPadding;
        LabelPartNameY = CodeDimension;
        CodePositionX1 = LabelDimension - CodeDimension - LabelInternalPadding;
        CodePositionY1 = LabelInternalPadding;
        LabelFieldsX = LabelInternalPadding * 2;
        LabelFieldsY = CodeDimension + TextSizeMedium + (LabelInternalPadding * 4);
    }

    /// <summary>
    /// Creates and returns a new, pure-white bitmap image to use as a Label base.
    /// </summary>
    /// <returns></returns>
    private static Bitmap LoadBase() 
    {
        // create a new white Label Base
        Bitmap Base = new Bitmap(1800, 1800, System.Drawing.Imaging.PixelFormat.Format32bppArgb);
        // create a new Drawing Surface and draw all white to the base
        using (Graphics Surface = Graphics.FromImage(Base)) 
        {
            Rectangle ImageSize = new(0, 0, 1800, 1800);
            Surface.FillRectangle(Brushes.White, ImageSize);
        }
        return Base;
    }
    
    /// <summary>
    /// Creates a new Image of a Production Lot Tracing Label that can be sent to Print Spooling.
    /// </summary>
    /// <exception cref="SystemException"></exception>
    public BasketLabel() 
    {
        // scale the Label dimensions to the current Device's Dpi Scale
        ConfigureLabelDimensions();
        // load a new Label base and load the Label fonts
        Image = LoadBase();
        FontFamily? Arial;
        try 
        {
            Arial = new FontFamily("Arial");
        } 
        catch 
        {
            throw new SystemException("Could not find Arial Font Group in the System.");
        }
        FontSmall = new System.Drawing.Font(Arial!, TextSizeSmall);
        FontMedium = new System.Drawing.Font(Arial!, TextSizeMedium);
        FontLarge = new System.Drawing.Font(Arial!, TextSizeLarge);
    }

    /// <summary>
    /// Access the current Bitmap image assigned to the Label object.
    /// </summary>
    /// <returns>A Bitmap image of the Label.</returns>
    public Bitmap GetImage() 
    {
        return Image;
    }

    /// <summary>
    /// Writes Header text to the top-left corner of the Label.
    /// </summary>
    /// <param name="HeadingText">The text to write.</param>
    /// <returns></returns>
    public async Task AddHeaderAsync(string HeadingText) 
    {
        // start a new CPU thread to apply the header to the LabelBase
        await Task.Run(() => 
        {
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Heading text
            Surface.DrawString(HeadingText, FontLarge, Brushes.Black, LabelHeadingX, LabelHeadingY);
            Surface.Flush();
        });
    }

    /// <summary>
    /// Writes PartName text below the Label Header.
    /// </summary>
    /// <param name="PartName"></param>
    /// <returns></returns>
    public async Task AddPartNameAsync(string PartName) 
    {
        // start a new CPU thread to apply the part name to the LabelBase
        await Task.Run(() => 
        {
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Part Name text
            Surface.DrawString(PartName, FontMedium, Brushes.Black, LabelPartNameX, LabelPartNameY);
            Surface.Flush();
        });
    }

    /// <summary>
    /// Adds a QR Code, as an image, to the top-right corner of the Label.
    /// </summary>
    /// <param name="LabelCode"></param>
    /// <returns></returns>
    public async Task AddQRCodeAsync(QRCode LabelCode) 
    {
        // start a new CPU thread to apply the QR code to the LabelBase
        await Task.Run(() => 
        {
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.CompositingMode = CompositingMode.SourceOver;
            Surface.CompositingQuality = CompositingQuality.HighQuality;
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            // resize and draw the QR Code
            Bitmap LabelCodeImage = Resizer.ResizeImage(LabelCode.CodeImage!, CodeDimension, CodeDimension);
            Surface.DrawImage(LabelCodeImage, CodePositionX1, CodePositionY1);
            Surface.Flush();
        });
    }

    /// <summary>
    /// Adds the data fields to the mid-to-bottom-left area of the Label.
    /// </summary>
    /// <param name="LabelFields"></param>
    /// <returns></returns>
    public async Task AddLabelFieldsAsync(List<string> LabelFields) 
    {
        // start a new CPU thread to apply the Label Fields to the LabelBase
        await Task.Run(() => 
        {
            // combine the LabelFields into a string deliniated by newlines
            string LabelFieldsBody = "";
            foreach (string _field in LabelFields) 
            {
                // if the field is the operator ID, do not include in the shown text
                if (_field.Contains("Operator")) 
                {
                    continue;
                // if the field is the Part info, do not include the Part Name
                } 
                else if (_field.Contains("Part")) 
                {
                    LabelFieldsBody += $"{_field.Split("\n")[0]}\n";
                // add the field as normal
                } 
                else 
                {
                    LabelFieldsBody += $"{_field}\n";
                }
            }
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Heading text
            Surface.DrawString(LabelFieldsBody, FontSmall, Brushes.Black, LabelFieldsX, LabelFieldsY);
            Surface.Flush();
        });
    }
}
# pragma warning restore CA1416 // Validate platform compatibility