using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;

namespace LotCoMPrinter.Models.Datasources;

# pragma warning disable CA1416 // Validate platform compatibility

public class PartialDataSetLabel 
{
    /// <summary>
    /// A LabelDimensions object that provides design constants for the Label.
    /// </summary>
    private readonly LabelDimensions Dimensions;

    /// <summary>
    /// A Bitmap image of the Label generated by the object's properties.
    /// </summary>
    private readonly Bitmap Image;

    /// <summary>
    /// The Font Group object for small text on the Label.
    /// </summary>
    private readonly System.Drawing.Font FontSmall;

    /// <summary>
    /// The Font Group object for medium text on the Label.
    /// </summary>
    private readonly System.Drawing.Font FontMedium;

    /// <summary>
    /// The Font Group object for large text on the Label.
    /// </summary>
    private readonly System.Drawing.Font FontLarge;

    /// <summary>
    /// Creates and returns a new, pure-white bitmap image to use as a Label base.
    /// </summary>
    /// <returns></returns>
    private static Bitmap LoadBase() 
    {
        // create a new white Label Base
        Bitmap Base = new Bitmap(1800, 1800, System.Drawing.Imaging.PixelFormat.Format32bppArgb);
        // create a new Drawing Surface and draw all white to the base
        using (Graphics Surface = Graphics.FromImage(Base)) 
        {
            Rectangle ImageSize = new(0, 0, 1800, 1800);
            Surface.FillRectangle(Brushes.White, ImageSize);
        }
        return Base;
    }
    
    /// <summary>
    /// Creates a new Image of a Partial Production Data Set Label that can be sent to Print Spooling.
    /// </summary>
    /// <exception cref="SystemException"></exception>
    public PartialDataSetLabel() 
    {
        // configure the Label's design dimensions
        Dimensions = new LabelDimensions
        (
            LabelDimensions.LabelSizes.Default,
            LabelDimensions.CodeSizes.Default,
            LabelDimensions.TextSizes.Tiny,
            LabelDimensions.TextSizes.Small,
            LabelDimensions.TextSizes.Medium,
            LabelDimensions.PaddingLevels.Thin,
            LabelDimensions.PaddingLevels.Thin - 56,
            LabelDimensions.PaddingLevels.Thin - 56,
            LabelDimensions.PaddingLevels.Thin,
            LabelDimensions.PaddingLevels.Thin - 56 + (LabelDimensions.TextSizes.Medium * 2) + LabelDimensions.PaddingLevels.Thin,
            0, // no QR Codes
            0, // no QR Codes
            LabelDimensions.PaddingLevels.Thin * 2,
            LabelDimensions.TextSizes.Medium + LabelDimensions.TextSizes.Small + (LabelDimensions.PaddingLevels.Thin * 4)
        );
        // load a new Label base and the Label's fonts
        Image = LoadBase();
        FontFamily? Arial;
        try 
        {
            Arial = new FontFamily("Arial");
        } 
        catch 
        {
            throw new SystemException("Could not find Arial Font Group in the System.");
        }
        FontSmall = new System.Drawing.Font(Arial!, Dimensions.TextSizeSmall);
        FontMedium = new System.Drawing.Font(Arial!, Dimensions.TextSizeMedium);
        FontLarge = new System.Drawing.Font(Arial!, Dimensions.TextSizeLarge);
    }

    /// <summary>
    /// Access the current Bitmap image assigned to the PartialLabel object.
    /// </summary>
    /// <returns>A Bitmap image of the Label.</returns>
    public Bitmap GetImage() 
    {
        return Image;
    }

    /// <summary>
    /// Writes a Partial Header to the top-left corner of the Label.
    /// </summary>
    /// <returns></returns>
    public async Task AddHeaderAsync() 
    {
        // start a new CPU thread to apply the header to the LabelBase
        await Task.Run(() => 
        {
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Heading text
            Surface.DrawString($"Partial Basket Info", FontLarge, Brushes.Black, Dimensions.HeadingHorizontalAnchor, Dimensions.HeadingVerticalAnchor);
            Surface.Flush();
        });
    }

    /// <summary>
    /// Writes PartName text below the Label Header.
    /// </summary>
    /// <param name="PartName"></param>
    /// <returns></returns>
    public async Task AddPartNameAsync(string PartName) 
    {
        // start a new CPU thread to apply the part name to the LabelBase
        await Task.Run(() => 
        {
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Part Name text
            Surface.DrawString(PartName, FontMedium, Brushes.Black, Dimensions.PartNameHorizontalAnchor, Dimensions.PartNameVerticalAnchor);
            Surface.Flush();
        });
    }

    /// <summary>
    /// Adds the data fields to the mid-to-bottom-left area of the Label.
    /// </summary>
    /// <param name="LabelFields"></param>
    /// <returns></returns>
    public async Task AddLabelFieldsAsync(List<string> LabelFields) 
    {
        // start a new CPU thread to apply the Label Fields to the LabelBase
        await Task.Run(() => 
        {
            // combine the LabelFields into a string deliniated by newlines
            string LabelFieldsBody = "";
            foreach (string _field in LabelFields) 
            {
                // add the field to the data body
                LabelFieldsBody += _field + "\n";
            }
            // create a drawing surface to draw the text with
            Graphics Surface = Graphics.FromImage(Image);
            // set the quality properties of the Surface
            Surface.SmoothingMode = SmoothingMode.AntiAlias;
            Surface.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Surface.PixelOffsetMode = PixelOffsetMode.HighQuality;
            Surface.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
            // draw the Heading text
            Surface.DrawString(LabelFieldsBody, FontSmall, Brushes.Black, Dimensions.BodyHorizontalAnchor, Dimensions.BodyVerticalAnchor);
            Surface.Flush();
        });
    }
}
# pragma warning restore CA1416 // Validate platform compatibility