name: CI Workflow

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '9.0.103' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install MAUI 
      run: dotnet workload install maui
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: latest-${{matrix.os}}-build
        path: |
          D:\a\LotCoM-printer\LotCoM-printer\LotCoMPrinter\bin\Debug\net9.0-windows*

  package:
    
    name: package-msix
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Package
      run: dotnet publish -f latest-build -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=MSIX -p:WindowsAppSDKSelfContained=true

    - name: Archive package artifact
      uses: actions/upload-artifact@v4
      with:
        name: latest-${{matrix.os}}-package
        path: |
          D:\a\LotCoM-printer\LotCoM-printer\LotCoMPrinter\bin\Release\net9.0-windows*\win10-x64\AppPackages\LotCoMPrinter*\LotCoMPrinter.msix
          

    
